// scripts/seed-test-user.ts
import { config } from 'dotenv';
config({ path: '.env.local' });   // <-- make sure we load .env.local
import { createClient } from '@supabase/supabase-js';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!; // service role ONLY for seeding

const admin = createClient(url, serviceKey)

async function main() {
  // 1) create auth user (id is generated by Supabase Auth)
  const email = 'test@example.com'
  const password = 'Test1234!' // local-only seed
  const { data: created, error: createErr } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { name: 'Test User' }
  })

  if (createErr && !/User already registered/i.test(createErr.message)) {
    console.error('createUser error:', createErr.message)
    process.exit(1)
  }

  // If user already exists, fetch it
  const userId =
    created?.user?.id ??
    (await (async () => {
      const { data } = await admin
        .from('profiles') // quicker path if profile exists
        .select('user_id')
        .eq('email', email)
        .maybeSingle()
      if (data?.user_id) return data.user_id

      // fallback: read from auth.users via RPC (not directly readable without PostgREST exposure)
      const { data: authUsers } = await admin
        .from('auth.users' as const) // if you've exposed it via PostgREST (often not)
        .select('id')
        .eq('email', email)
        .limit(1)
      // Note: auth.users table is typically not accessible via PostgREST
      return authUsers?.[0]?.id
    })())

  if (!userId) {
    console.error('Could not resolve test user id; aborting.')
    process.exit(1)
  }

  // 2) upsert profile row linked to the real auth user id
  const { error: upsertErr } = await admin.from('profiles').upsert(
    {
      user_id: userId,
      email,
      full_name: 'Test User',
      attachment_style: 'secure',
      love_languages: ['words', 'time']
    },
    { onConflict: 'user_id' }
  )

  if (upsertErr) {
    console.error('profiles upsert error:', upsertErr.message)
    process.exit(1)
  }

  console.log('✅ Seeded test user & profile:', { email, userId })
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
